import Image from "next/image";

import { publicUrl } from "@/lib/storage";

/**
 * The generated illustration beside a night's column.
 *
 * Sized by the caller, and deliberately never large. These are synthetic, and a
 * fabricated photograph running at full width asserts more than it has earned:
 * it should sit beside the writing the way a wire photo does, not lead the page.
 * Callers pass a max width.
 *
 * The only way this image is rendered anywhere on the site, which is deliberate.
 * It carried a visible "AI interpretation" caption until it was removed at the
 * user's request. What labelling remains is the alt text, which names it as a
 * generated illustration, and the figure's title, which says it is not a
 * photograph of the match. Both are attached here rather than at the call site
 * for the original reason: there is no way to ask for the picture without them.
 *
 * Renders nothing at all when there is no image or when storage is unconfigured,
 * rather than a broken frame. Same honest degradation as `publicUrl` elsewhere.
 */
export function ColumnImage({
  imageKey,
  model,
  headline,
  priority = false,
  className = "",
}: {
  imageKey: string | null;
  /**
   * Which model made it. No longer printed under the picture, because the full
   * sentence was taller than a thumbnail, but kept as the figure's title so the
   * provenance is a hover away rather than gone. Also on the row in
   * `night_columns.image_model`.
   */
  model: string | null;
  /** Used for the alt text, so a screen reader gets the article, not the file. */
  headline: string;
  priority?: boolean;
  className?: string;
}) {
  const src = imageKey ? publicUrl(imageKey) : null;
  if (!src) return null;

  return (
    <figure
      className={className}
      title={
        model
          ? `Generated by ${model}. Not a photograph of the match.`
          : "Generated. Not a photograph of the match."
      }
    >
      <div className="relative aspect-[16/9] w-full overflow-hidden rounded-sm border border-basalt-800 bg-basalt-900">
        <Image
          src={src}
          alt={`Generated illustration for the report headlined: ${headline}`}
          fill
          sizes="(min-width: 1024px) 640px, 100vw"
          priority={priority}
          className="object-cover"
        />
      </div>
    </figure>
  );
}
