/**
 * What reference images exist in the bucket.
 *
 * GENERATED by `npm run refs:push`. Edit the files in `assets/refs` and run it
 * again rather than editing this by hand, or the manifest and the bucket drift
 * apart and the drift shows up as a missing picture weeks later.
 *
 * The images themselves are not in the repo; this is the record of what they are.
 * Set fingerprint 645b76a1711f.
 *
 * `MAP_ALIASES` is the one part worth editing by hand: it maps the map names the
 * server actually reports onto the folders here, so variants that share their
 * geometry share their screenshots.
 */

export type CharacterRef = {
  team: "red" | "blue";
  /**
   * What the body is doing, so the pose can be matched to the moment: a capture
   * run wants `run`, a defensive stand wants `crouch`, a celebration wants
   * somebody upright. Labelled by `npm run refs:label`, which looks at the
   * picture, because a batch export from a model viewer says nothing in its
   * filename.
   *
   * `tpose` is a rig reference rather than a person doing something, and its
   * splayed arms carry into whatever it conditions. Used only as a last resort.
   */
  pose:
    | "stance"
    | "aim"
    | "walk"
    | "run"
    | "crouch"
    | "death"
    | "jump"
    | "idle"
    | "tpose"
    | "other";
  facing: "front" | "back" | "side" | "angle" | "alt";
  key: string;
};

export type FlagRef = {
  team: "red" | "blue";
  facing: "front" | "back" | "side" | "angle" | "alt";
  key: string;
};

export type MapShot = { area: string; key: string };

export const CHARACTERS: CharacterRef[] = [
  { team: "blue", pose: "aim", facing: "side", key: "refs/characters/blue-aim-side-01.png" },
  { team: "blue", pose: "crouch", facing: "angle", key: "refs/characters/blue-crouch-angle-01.png" },
  { team: "blue", pose: "crouch", facing: "front", key: "refs/characters/blue-crouch-front-01.png" },
  { team: "blue", pose: "death", facing: "angle", key: "refs/characters/blue-death-angle-01.png" },
  { team: "blue", pose: "death", facing: "angle", key: "refs/characters/blue-death-angle-02.png" },
  { team: "blue", pose: "death", facing: "side", key: "refs/characters/blue-death-side-01.png" },
  { team: "blue", pose: "jump", facing: "angle", key: "refs/characters/blue-jump-angle-01.png" },
  { team: "blue", pose: "jump", facing: "angle", key: "refs/characters/blue-jump-angle-02.png" },
  { team: "blue", pose: "run", facing: "angle", key: "refs/characters/blue-run-angle-01.png" },
  { team: "blue", pose: "run", facing: "angle", key: "refs/characters/blue-run-angle-02.png" },
  { team: "blue", pose: "run", facing: "angle", key: "refs/characters/blue-run-angle-03.png" },
  { team: "blue", pose: "run", facing: "side", key: "refs/characters/blue-run-side-01.png" },
  { team: "blue", pose: "stance", facing: "angle", key: "refs/characters/blue-stance-angle-01.png" },
  { team: "blue", pose: "stance", facing: "angle", key: "refs/characters/blue-stance-angle-02.png" },
  { team: "blue", pose: "stance", facing: "front", key: "refs/characters/blue-stance-front-01.png" },
  { team: "blue", pose: "tpose", facing: "angle", key: "refs/characters/blue-tpose-angle-01.png" },
  { team: "blue", pose: "tpose", facing: "back", key: "refs/characters/blue-tpose-back-01.png" },
  { team: "blue", pose: "tpose", facing: "front", key: "refs/characters/blue-tpose-front-01.png" },
  { team: "blue", pose: "tpose", facing: "side", key: "refs/characters/blue-tpose-side-01.png" },
  { team: "blue", pose: "walk", facing: "side", key: "refs/characters/blue-walk-side-01.png" },
  { team: "red", pose: "crouch", facing: "angle", key: "refs/characters/red-crouch-angle-01.png" },
  { team: "red", pose: "crouch", facing: "angle", key: "refs/characters/red-crouch-angle-02.png" },
  { team: "red", pose: "crouch", facing: "front", key: "refs/characters/red-crouch-front-01.png" },
  { team: "red", pose: "crouch", facing: "side", key: "refs/characters/red-crouch-side-01.png" },
  { team: "red", pose: "death", facing: "angle", key: "refs/characters/red-death-angle-01.png" },
  { team: "red", pose: "death", facing: "angle", key: "refs/characters/red-death-angle-02.png" },
  { team: "red", pose: "death", facing: "angle", key: "refs/characters/red-death-angle-03.png" },
  { team: "red", pose: "death", facing: "back", key: "refs/characters/red-death-back-01.png" },
  { team: "red", pose: "death", facing: "side", key: "refs/characters/red-death-side-01.png" },
  { team: "red", pose: "run", facing: "angle", key: "refs/characters/red-run-angle-01.png" },
  { team: "red", pose: "run", facing: "angle", key: "refs/characters/red-run-angle-02.png" },
  { team: "red", pose: "run", facing: "angle", key: "refs/characters/red-run-angle-03.png" },
  { team: "red", pose: "run", facing: "side", key: "refs/characters/red-run-side-01.png" },
  { team: "red", pose: "stance", facing: "angle", key: "refs/characters/red-stance-angle-01.png" },
  { team: "red", pose: "stance", facing: "angle", key: "refs/characters/red-stance-angle-02.png" },
  { team: "red", pose: "stance", facing: "front", key: "refs/characters/red-stance-front-01.png" },
  { team: "red", pose: "tpose", facing: "angle", key: "refs/characters/red-tpose-angle-01.png" },
  { team: "red", pose: "tpose", facing: "back", key: "refs/characters/red-tpose-back-01.png" },
  { team: "red", pose: "tpose", facing: "front", key: "refs/characters/red-tpose-front-01.png" },
  { team: "red", pose: "tpose", facing: "side", key: "refs/characters/red-tpose-side-01.png" },
  { team: "red", pose: "walk", facing: "angle", key: "refs/characters/red-walk-angle-01.png" },
  { team: "red", pose: "walk", facing: "angle", key: "refs/characters/red-walk-angle-02.png" },
];

export const FLAGS: FlagRef[] = [
  { team: "blue", facing: "alt", key: "refs/flags/blue-alt-01.png" },
  { team: "blue", facing: "back", key: "refs/flags/blue-back-01.png" },
  { team: "blue", facing: "front", key: "refs/flags/blue-front-01.png" },
  { team: "blue", facing: "side", key: "refs/flags/blue-side-01.png" },
  { team: "red", facing: "alt", key: "refs/flags/red-alt-01.png" },
  { team: "red", facing: "back", key: "refs/flags/red-back-01.png" },
  { team: "red", facing: "front", key: "refs/flags/red-front-01.png" },
  { team: "red", facing: "side", key: "refs/flags/red-side-01.png" },
];

export const MAP_SHOTS: Record<string, MapShot[]> = {
  "ankh-b12": [
    { area: "blue-flagroom", key: "refs/maps/ankh-b12/blue-flagroom-01.jpg" },
    { area: "mid", key: "refs/maps/ankh-b12/mid-01.jpg" },
    { area: "red-flagroom", key: "refs/maps/ankh-b12/red-flagroom-01.jpg" },
    { area: "mid-alt", key: "refs/maps/ankh-b12/mid-alt-01.jpg" },
    { area: "overview", key: "refs/maps/ankh-b12/overview-01.jpg" },
  ],
  "dark-warlords": [
    { area: "mid", key: "refs/maps/dark-warlords/mid-01.jpg" },
    { area: "blue-flagroom", key: "refs/maps/dark-warlords/blue-flagroom-01.jpg" },
    { area: "red-flagroom", key: "refs/maps/dark-warlords/red-flagroom-01.jpg" },
    { area: "mid-alt", key: "refs/maps/dark-warlords/mid-alt-01.jpg" },
    { area: "overview", key: "refs/maps/dark-warlords/overview-01.jpg" },
  ],
  "huna-b8": [
    { area: "overview", key: "refs/maps/huna-b8/overview-01.jpg" },
    { area: "blue-flagroom", key: "refs/maps/huna-b8/blue-flagroom-01.jpg" },
    { area: "mid", key: "refs/maps/huna-b8/mid-01.jpg" },
    { area: "red-flagroom", key: "refs/maps/huna-b8/red-flagroom-01.jpg" },
  ],
  "rail-fight": [
    { area: "blue-flagroom", key: "refs/maps/rail-fight/blue-flagroom-01.jpg" },
    { area: "red-flagroom", key: "refs/maps/rail-fight/red-flagroom-01.jpg" },
  ],
  "relic-seeker": [
    { area: "blue-flagroom", key: "refs/maps/relic-seeker/blue-flagroom-01.jpg" },
    { area: "mid", key: "refs/maps/relic-seeker/mid-01.jpg" },
    { area: "red-flagroom", key: "refs/maps/relic-seeker/red-flagroom-01.jpg" },
  ],
  "shattered-gorge-mini": [
    { area: "overview", key: "refs/maps/shattered-gorge-mini/overview-01.jpg" },
  ],
  "warlords-pro": [
    { area: "overview", key: "refs/maps/warlords-pro/overview-01.jpg" },
    { area: "blue-flagroom", key: "refs/maps/warlords-pro/blue-flagroom-01.jpg" },
    { area: "mid", key: "refs/maps/warlords-pro/mid-01.jpg" },
    { area: "red-flagroom", key: "refs/maps/warlords-pro/red-flagroom-01.jpg" },
  ],
};

/**
 * Map names as the server reports them, mapped onto the folders above.
 *
 * Hand maintained. An unknown map is not an error: the illustration falls back to
 * having no scene reference, which is a worse picture rather than no picture.
 */
export const MAP_ALIASES: Record<string, string> = {
  "ankh b12": "ankh-b12",
  "huna b8": "huna-b8",
  "dark warlords": "dark-warlords",
  "relic seeker": "relic-seeker",
  "shattered gorge mini v2.1": "shattered-gorge-mini",
  "warlords pro (no amp)": "warlords-pro",
  "warlords pro (no fog)": "warlords-pro",
  "rail fight": "rail-fight",
};

/** Looks up a map's screenshots by the name the server reported. */
export function shotsForMap(mapName: string): MapShot[] {
  const slug = MAP_ALIASES[mapName.trim().toLowerCase()];
  return slug ? (MAP_SHOTS[slug] ?? []) : [];
}
